### ISSUE TITLE
Unable to authenticate. Receive (401) Unauthorized.

### ISSUE THREAD

**Issue by fyrhol** [christaylorcodes/ConnectWiseControlAPI#5]
Hi there Chris.

I came across this API and was hoping I could get it working but unfortunately I haven't had much success.
I think it's because of the 2FA requirement, possibly? The user account I'm trying with is simply set up with the Internal user source, but it us using email for the OTP.

Below is the error I get.

```
$Computer = Get-CWCSession -Type Access -Search 'Computer201' -Limit 1


Invoke-CWCWebRequest : An exception has been thrown.
--> The remote server returned an error: (401) Unauthorized.
An error has been thrown.
-->
--> {"errorType":"SecurityException","message":"Needs permission","detail":null}
at Invoke-CWCWebRequest, C:\Program Files\WindowsPowerShell\Modules\ConnectWiseControlAPI\0.1.2.0\Private\Invoke-CWCWebRequest.ps1: line 20
at Get-CWCSession, C:\Program Files\WindowsPowerShell\Modules\ConnectWiseControlAPI\0.1.2.0\Public\PageService\Get-CWCSession.ps1: line 30
at <ScriptBlock>, <No file>: line 1
At C:\Program Files\WindowsPowerShell\Modules\ConnectWiseControlAPI\0.1.2.0\Public\PageService\Get-CWCSession.ps1:30 char:14
+     $Data =  Invoke-CWCWebRequest -Arguments $WebRequestArguments
+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-CWCWebRequest
```

If it indeed is the fact that this API cannot handle the passing through of the OTP code, is there any chance you could take a look at implementing this?
I'd be more than happy to put in a significant donation for your troubles, as getting this API working would be a life saver.

Thanks!

**Comment by forminasage** [comment]
@fyrhol try using `Connect-CWC -Force`

**Comment by fyrhol** [comment]
> @fyrhol try using `Connect-CWC -Force`

Thanks @forminasage 
Unfortunately this did not help. I'm fairly sure it's to do with the requirement of the MFA code.
As seen at [this document](https://docs.connectwise.com/ConnectWise_Control_Documentation/Technical_support_bulletins/Email_and_two-factor_authentication_required), all cloud instance 'internal users' require OTP turned on. 

I appreciate the input though.

**Comment by enigmaoftech** [comment]
I'm having the same issue. We have on prem but utilize DUO MFA. It pushes auth through to fast for me to approve it. Any way to handle MFA?

**Comment by jazzbanzai** [comment]
When you make a user, you don't have to set 2FA. 
Although Admin users will get bugged to set it up every time you log in, even as another user. 
See: https://docs.connectwise.com/ConnectWise_Control_Documentation/Technical_support_bulletins/Additional_security_requirement_for_internal_user_accounts

"Note: This prompt only appears for Cloud Account Administrators and users with the **Administer** permission on ConnectWise Control Cloud."

**Comment by christaylorcodes** [comment]
An account without MFA is required. Added to requirements in the readme.

**Comment by radishimo** [comment]
Is this inherit to ConnectWise inability to process mfa thru api? They are
working on enforcing mfa soon, so with this process change at some point?
